WebApplication2/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor.Compilation;
using MySql.Data.MySqlClient;
using MyTested.AspNetCore.Mvc.Builders.Controllers;
using WebApplication2.Ado;
using WebApplication2.Models;

namespace WebApplication2.Controllers;

[Route("[controller]")]
public class CustomerController : Controller
{
    private readonly IDataContext _dataContext;
    public CustomerController() {
        var connectionStringBuilder = new MySqlConnectionStringBuilder {
            Server = "localhost",
            Database = "productsdb",
            UserID = "root",
            Password = "Volk5801"
        };

        //_dataContext = new RawSqlDataContext("Datasource=localhost;Database=shop;User=root;Password=root123;");
        _dataContext = new AdoDataContext(connectionStringBuilder.ConnectionString);
    }
    public readonly AppDbContext db = new AppDbContext();

    
    public IActionResult Customer()
    {
        return View(db.SelectCustomers());
    }

    [HttpPost("{id}")]
    public Customer UpdateCustomer([FromRoute] int id, [FromBody] Customer customer)
    {
        db.UpdateCustomer(customer.Id, customer);
        return db.SelectCustomers().FirstOrDefault(x => x.Id == customer.Id);

    }
}

WebApplication2/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor.Compilation;
using MySql.Data.MySqlClient;
using MyTested.AspNetCore.Mvc.Builders.Controllers;
using WebApplication2.Ado;
using WebApplication2.Models;

namespace WebApplication2.Controllers;

[Route("[controller]")]
public class OrderController : Controller
{
    public readonly AppDbContext db = new AppDbContext();
    
    public IActionResult Orders()
    {
        var orders = db.SelectOrders();
        return View(orders);
    }
 
}

WebApplication2/Views/Shared/_Layout.cshtml
@using System.Collections.Specialized

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Products</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Customer">Customers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Orders">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
        @ViewData["Input"]
    </main>
</div>


<footer class="border-top footer text-muted">
    <div class="container">
        @if (IsSectionDefined("Footer"))
        {
            @await RenderSectionAsync("Footer", false) <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        }
        else
        {
            <div> Дефолтный - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> </div>
        }
           
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication2/Views/Shared/_MyLayout.cshtml
@using System.Collections.Specialized

<!DOCTYPE html>
<html lang="en">
<head >
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
        
        <div class="container-fluid">
            <p>MyLayout</p>
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                        <H5>Products</H5></a>
                    </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Customer">
                        <H5>Customers</H5></a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Orders">
                        <H5>Orders</H5></a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">
                        <H5>Privacy</H5></a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
         @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        @await RenderSectionAsync("Footer", false)  <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>